name: Deploy DataFlow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID_D_APIM:
        required: true
      AZURE_CLIENT_SECRET_D_APIM:
        required: true
      AZURE_SUBSCRIPTION_ID_D_APIM:
        required: true
      AZURE_TENANT_ID_D_APIM:
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: >
                {
                  "clientId":"${{ secrets.AZURE_CLIENT_ID_D_APIM }}",
                  "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET_D_APIM }}",
                  "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID_D_APIM }}",
                  "tenantId":"${{ secrets.AZURE_TENANT_ID_D_APIM }}"
                }
          enable-AzPSSession: true

      - name: Read pipeline dataflow JSON files and deploy
        run: |
          # Ensure the correct path to the JSON files
          dataflow1=$(cat ./dataflow/dataflow2.json)

          # Construct a JSON array with the dataflow contents
          dataflows=$(jq -n \
            --arg dataflow1 "$dataflow1" \
            '[
              {
                "name": "dataflow2",
                "definition": $dataflow1 | fromjson
              }
            ]')

          # Deploy using Bicep (or ARM template)
          az deployment group create \
            --resource-group "komatsu" \
            --template-file ./bicep/modules/dataflow.bicep \
            --parameters dataFactoryName=DMJTest \
            --parameters dataflows="$dataflows"