name: Deploy ADF LinkedService

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
env:
  keyVaultName: 'kx1-demo-dev'
  connectionSecretName: 'kx-demo-constring-dev'
  credentialSecretName: 'kx-demo-cred-dev'
  
jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      env:
          CONNECTION_STRING: '' 
      run: |
          echo "Name: $CONNECTION_STRING"

    - name: Install jq
      run: sudo apt-get install jq

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
              }
        enable-AzPSSession: true
    

    - name: Repo Var Test 
      run: echo "DJ=${{ vars.TEST }}"

    # - name: Get Key Vault Secrets
    #   id: kv-secrets
    #   uses: Azure/get-keyvault-secrets@v1 
    #   with:
    #     keyvault: "kx1-demo-dev"
    #     secrets: "kx-demo-constring-dev"

      # with:
      #   vault-name: "kx1-demo-dev"
      #   secrets: |
      #     "kx-demo-constring-dev"          
          
    # - name: Fetch secrets from Azure Key Vault
    #   id: fetch-secrets
    #   run: |
    #     # Set the Key Vault and secret names
    #     KEY_VAULT_NAME="kx1-demo-dev"
    #     SECRET_NAME="kx-demo-constring-dev"

    #     # Fetch the secret using Azure CLI
    #     CONNECTION_STRING=$(az keyvault secret show --name $SECRET_NAME --vault-name $KEY_VAULT_NAME --query value -o tsv)

    #     # Set the secret as an environment variable for later use
    #     echo "CONNECTION_STRING=$CONNECTION_STRING"

    - name: Read linkedService JSON files and deploy
      run: |
        keyVaultLinkedService = $(cat ./linkedService/AzureKeyVault1.json)
        keyVaultLinkedService = $(echo "$keyVaultLinkedService" | jq --arg keyVaultUrl "https://{{$env.keyVaultName}}.azure.net/" '.properties.typeProperties.baseUrl = $keyVaultUrl')
        linkedService1=$(cat ./linkedService/AzureBlobStorage1.json)
        linkedService1=$(echo "$linkedService1" | jq --arg connectionSecretName "$env.connectionSecretName" '.properties.typeProperties.connectionString.secretName = $connectionSecretName')  
        linkedService1=$(echo "$linkedService1" | jq --arg credentialSecretName "$env.credentialSecretName" '.properties.typeProperties.encryptedCredential.secretName = $credentialSecretName')  
       
        linkedServices=$(jq -n \
          --arg keyVaultLinkedService "$keyVaultLinkedService" \
          --arg linkedService1 "$linkedService1" \
          '[
            {
              "name": "AzureKeyVault1", 
              "definition": $keyVaultLinkedService | fromjson 
            },
            {
              "name": "AzureBlobStorage1", 
              "definition": $linkedService1 | fromjson 
            }
          ]')

        az deployment group create \
          --resource-group "komatsu" \
          --template-file ./bicep/modules/linkedservice.bicep \
          --parameters dataFactoryName=ssdsss \
          --parameters linkedServices="$linkedServices" \
          --parameters encryptedCredential=${{ vars.TEST }}
          
