name: Deploy ADF Trigger

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID_D_APIM:
        required: true
      AZURE_CLIENT_SECRET_D_APIM:
        required: true
      AZURE_SUBSCRIPTION_ID_D_APIM:
        required: true
      AZURE_TENANT_ID_D_APIM:
        required: true


jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID_D_APIM }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET_D_APIM }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID_D_APIM }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID_D_APIM }}"
              }
        enable-AzPSSession: true  # Make sure to store your Azure credentials as secrets

    - name: Read Trigger JSON files and deploy
      run: |
          # Ensure the correct path to the JSON files
          TestTrigger1=$(cat ./trigger/ADFtrigger.json)

          # Construct a JSON array with the Trigger contents
          TestTrigger=$(jq -n \
            --arg TestTrigger1 "$TestTrigger1" \
            '[
              {
                "name": "ADFtrigger",
                "definition": $TestTrigger1 | fromjson
              }
            ]')

          # Deploy using Bicep (or ARM template)
          az deployment group create \
            --resource-group "komatsu" \
            --template-file ./bicep/modules/trigger.bicep \
            --parameters dataFactoryName=DMJTest \
            --parameters triggers="$TestTrigger"